export function buildFlowControllerInitParams(ctx) {
  return {
    audioFlowController: ctx.audioFlowController,
    uiFlowController: ctx.uiFlowController,
    gestureFlowController: ctx.gestureFlowController,
    settingsFlowController: ctx.settingsFlowController,
    createAudioFlowController: ctx.createAudioFlowController,
    createUIFlowController: ctx.createUIFlowController,
    createGestureFlowController: ctx.createGestureFlowController,
    createSettingsFlowController: ctx.createSettingsFlowController,
    els: ctx.els,
    activeStepCount: ctx.activeStepCount,
    activeBeadMinIndex: ctx.activeBeadMinIndex,
    activeBeadMaxIndex: ctx.activeBeadMaxIndex,
    state: ctx.state,
    t: ctx.t,
    clamp: ctx.clamp,
    getStyleLabel: ctx.getStyleLabel,
    getSoundIconSvg: ctx.getSoundIconSvg,
    getAudioManager: ctx.getAudioManager,
    getModalManager: ctx.getModalManager,
    getUIRenderer: ctx.getUIRenderer,
    getBeadRenderManager: ctx.getBeadRenderManager,
    getGestureController: ctx.getGestureController,
    getWheelIndex: ctx.getWheelIndex,
    setWheelIndex: ctx.setWheelIndex,
    getLocks: ctx.getLocks,
    setLocks: ctx.setLocks,
    displayStep: ctx.displayStep,
    applyVisualStyles: ctx.applyVisualStyles,
    syncBeadStyleOptionState: ctx.syncBeadStyleOptionState,
    syncBackgroundStyleOptionState: ctx.syncBackgroundStyleOptionState,
    syncSoundModeOptionState: ctx.syncSoundModeOptionState,
    persistAndRender: ctx.persistAndRender,
    closeBeadStyleModal: ctx.closeBeadStyleModal,
    closeSoundModeModal: ctx.closeSoundModeModal,
    beadStyles: ctx.beadStyles,
    backgroundStyles: ctx.backgroundStyles,
    soundModes: ctx.soundModes,
  };
}

export function buildManagerInitParams(ctx) {
  return {
    modalManager: ctx.modalManager,
    beadRenderManager: ctx.beadRenderManager,
    uiRenderer: ctx.uiRenderer,
    assetsManager: ctx.assetsManager,
    controlsManager: ctx.controlsManager,
    audioManager: ctx.audioManager,
    gestureController: ctx.gestureController,
    ensureModalManager: ctx.ensureModalManager,
    ensureBeadRenderManager: ctx.ensureBeadRenderManager,
    ensureUIRenderer: ctx.ensureUIRenderer,
    ensureAssetsManager: ctx.ensureAssetsManager,
    ensureControlsManager: ctx.ensureControlsManager,
    ensureAudioManager: ctx.ensureAudioManager,
    ensureGestureController: ctx.ensureGestureController,
    createModalManager: ctx.createModalManager,
    createBeadRenderManager: ctx.createBeadRenderManager,
    createUIRenderer: ctx.createUIRenderer,
    createAssetsManager: ctx.createAssetsManager,
    createControlsManager: ctx.createControlsManager,
    createAudioManager: ctx.createAudioManager,
    createGestureController: ctx.createGestureController,
    els: ctx.els,
    activeStepCount: ctx.activeStepCount,
    activeBeadMinIndex: ctx.activeBeadMinIndex,
    activeBeadMaxIndex: ctx.activeBeadMaxIndex,
    visualBeadMinIndex: ctx.visualBeadMinIndex,
    visualBeadMaxIndex: ctx.visualBeadMaxIndex,
    terminalBeadLowIndex: ctx.terminalBeadLowIndex,
    terminalBeadHighIndex: ctx.terminalBeadHighIndex,
    desktopBeadSizePx: ctx.desktopBeadSizePx,
    mobileBeadSizePx: ctx.mobileBeadSizePx,
    beadGapPx: ctx.beadGapPx,
    knotAspectRatio: ctx.knotAspectRatio,
    onWheelLivePreview: ctx.onWheelLivePreview,
    isCoarsePointer: ctx.isCoarsePointer,
    getSoundIconSvg: ctx.getSoundIconSvg,
    beadStyles: ctx.beadStyles,
    beadImageSrcs: ctx.beadImageSrcs,
    backgroundStyles: ctx.backgroundStyles,
    backgroundImageSrcs: ctx.backgroundImageSrcs,
    backgroundImageByStyle: ctx.backgroundImageByStyle,
    knotImageSrc: ctx.knotImageSrc,
    terminalBeadStyleSrc: ctx.terminalBeadStyleSrc,
    terminalTailSrc: ctx.terminalTailSrc,
    stepSoundSrc: ctx.stepSoundSrc,
    mantraSrcM4A: ctx.mantraSrcM4A,
    mantraSrcMP3: ctx.mantraSrcMP3,
    mantraUnlockEarlySec: ctx.mantraUnlockEarlySec,
    onLockStateChange: ctx.onLockStateChange,
    swipeThresholdPx: ctx.swipeThresholdPx,
    wheelMinStepTriggerRatio: ctx.wheelMinStepTriggerRatio,
    getBeadPitch: ctx.getBeadPitch,
    getWheelIndex: ctx.getWheelIndex,
    setWheelIndex: ctx.setWheelIndex,
    getCurrentBeadIndex: ctx.getCurrentBeadIndex,
    requestRender: ctx.requestRender,
    stopSettleAnimation: ctx.stopSettleAnimation,
    initStepAudio: ctx.initStepAudio,
    isStepBlocked: ctx.isStepBlocked,
    setDragging: ctx.setDragging,
    onCancel: ctx.onCancel,
    onSettle: ctx.onSettle,
  };
}

export function buildRuntimeEventHandlers(ctx) {
  return {
    onReset: ctx.onReset,
    onOpenBeadStyle: () => ctx.modalManager()?.openBeadStyleModal(),
    onOpenSoundMode: () => ctx.modalManager()?.openSoundModeModal(),
    onCloseBeadStyle: () => ctx.modalManager()?.closeBeadStyleModal(),
    onBeadStyleBackdropClick: (event) => ctx.modalManager()?.onBeadStyleBackdropClick(event),
    onBeadStyleOptionClick: (event) => ctx.settingsFlowController()?.onBeadStyleOptionClick(event),
    onBackgroundStyleOptionClick: (event) => ctx.settingsFlowController()?.onBackgroundStyleOptionClick(event),
    onCloseSoundMode: () => ctx.modalManager()?.closeSoundModeModal(),
    onSoundModeBackdropClick: (event) => ctx.modalManager()?.onSoundModeBackdropClick(event),
    onSoundModeOptionClick: (event) => ctx.settingsFlowController()?.onSoundModeOptionClick(event),
    onCloseResetConfirm: () => ctx.modalManager()?.closeResetConfirmModal(),
    onConfirmReset: ctx.onConfirmReset,
    onResetConfirmBackdropClick: (event) => ctx.modalManager()?.onResetConfirmBackdropClick(event),
    onNextRound: ctx.onNextRound,
    onEscapeKey: (event) => ctx.modalManager()?.onEscapeKey(event),
    onInitStepAudio: () => ctx.audioFlowController()?.initStepAudio(),
    onPointerDown: (event) => ctx.gestureFlowController()?.onPointerDown(event),
    onPointerMove: (event) => ctx.gestureFlowController()?.onPointerMove(event),
    onPointerUp: (event) => ctx.gestureFlowController()?.onPointerUp(event),
    onPointerCancel: (event) => ctx.gestureFlowController()?.onPointerCancel(event),
    onResize: () => ctx.gestureFlowController()?.onResize(),
  };
}

export function buildRoundFlowInitParams(ctx) {
  return {
    roundFlowController: ctx.roundFlowController,
    state: ctx.state,
    stateDomainConfig: ctx.stateDomainConfig,
    activeStepCount: ctx.activeStepCount,
    activeBeadMinIndex: ctx.activeBeadMinIndex,
    activeBeadMaxIndex: ctx.activeBeadMaxIndex,
    dragCommitMinPx: ctx.dragCommitMinPx,
    wheelMomentumMs: ctx.wheelMomentumMs,
    wheelMinSettleMs: ctx.wheelMinSettleMs,
    wheelMaxSettleMs: ctx.wheelMaxSettleMs,
    roundLoaderMs: ctx.roundLoaderMs,
    computeSettleTarget: ctx.computeSettleTarget,
    clamp: ctx.clamp,
    resetProgress: ctx.resetProgress,
    advanceRound: ctx.advanceRound,
    getWheelIndex: ctx.getWheelIndex,
    setWheelIndex: ctx.setWheelIndex,
    getBeadPitch: ctx.getBeadPitch,
    getSoundMode: ctx.getSoundMode,
    applyStepDelta: ctx.applyStepDelta,
    animateOffset: ctx.animateOffset,
    animateWheelTo: ctx.animateWheelTo,
    triggerHaptic: ctx.triggerHaptic,
    onStepCommitted: ctx.onStepCommitted,
    stopMantraPlayback: ctx.stopMantraPlayback,
    stopStepPlayback: ctx.stopStepPlayback,
    isRoundLoaderOpen: ctx.isRoundLoaderOpen,
    openRoundLoader: ctx.openRoundLoader,
    closeRoundLoader: ctx.closeRoundLoader,
    openResetConfirmModal: ctx.openResetConfirmModal,
    closeResetConfirmModal: ctx.closeResetConfirmModal,
    requestRender: ctx.requestRender,
    displayStep: ctx.displayStep,
    updateCounterText: ctx.updateCounterText,
    saveState: ctx.saveState,
    render: ctx.render,
  };
}
